#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpCalBgoMip, 2014-09-11 16:02:43 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpAlgBgoDacor as DmpBgoDacor

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.Set("EventNumber","8008")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Warning")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.Set("Input/FileName","DmpRdcData.root")        # save output into input root file, if you really need
DMPSW.RootIOSvc.Set("Output/FileName","./test/Dacor.root")        # must set it, if NOT set, will not save anything
DMPSW.RootIOSvc.Set("Output/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
calBgoDacor = DmpBgoDacor.DmpAlgBgoDacor()
DMPSW.AlgMgr.Append(calBgoDacor)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

